name: Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Neovim
      run: sudo snap install nvim --classic

    - name: Install Plenary
      run: |
        mkdir -p $HOME/.local/share/nvim/lazy/
        git clone https://github.com/nvim-lua/plenary.nvim.git
        mv plenary.nvim $HOME/.local/share/nvim/lazy/

    - name: Install nvim-treesitter and parsers
      run: |
        mkdir -p $HOME/.local/share/nvim/lazy/
        git clone https://github.com/nvim-treesitter/nvim-treesitter.git
        mv nvim-treesitter $HOME/.local/share/nvim/lazy/
        nvim --headless --noplugin -u tests/minimal_init.lua -c "TSInstall! python rust" -c "quit"

    - name: Run luacheck type check
      run: |
        sudo apt-get install lua-check -y --no-install-recommends
        make typecheck

    - name: Run Tests
      run: make test

