name: Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Prepare apt
      run: |
        sudo apt-get update

    - name: Install Make Dependencies
      run: |
        sudo apt-get install libtool-bin autoconf automake cmake g++ pkg-config unzip gettext curl -y

    - name: Install Neovim
      run: |
        sudo snap install nvim --classic

    - name: Install Plenary
      run: |
        mkdir -p $HOME/.local/share/nvim/lazy/
        git clone https://github.com/nvim-lua/plenary.nvim.git
        mv plenary.nvim $HOME/.local/share/nvim/lazy/

    - name: Install luacheck
      run: |
        sudo apt-get install lua-check -y

    - name: Run Tests
      run: |
        make test

    - name: Ensure No util.R in code
      run: |
        make ensure-no-util-r

    - name: Run type check
      run: |
        make typecheck

